services:
  # OpenTelemetry Collector - トレースを収集してX-Rayに転送
  otel-collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config-xray.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-dummy}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-dummy}
      - AWS_REGION=ap-northeast-1

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: sbcntrapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sbcntrapp
    ports:
      - "5433:5432"  # ホストポート5433を使用（5432が既に使用中の場合）
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

volumes:
  postgres_data: