FROM fluent/fluent-bit:4.0.0-arm64

COPY ./fluent-bit-custom.conf /fluent-bit/custom.conf
COPY ./myparsers.conf /fluent-bit/myparsers.conf
COPY ./stream_processor.conf /fluent-bit/stream_processor.conf
