services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sbcntrapp
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sbcntrapp
      MYSQL_PASSWORD: password
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf